-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, sum(SALES_AMOUNT)*p.PRICE as SALES
from PRODUCT p join OFFLINE_SALE o on p.PRODUCT_ID=o.PRODUCT_ID
group by o.PRODUCT_ID
order by sum(SALES_AMOUNT)*p.PRICE desc, p.PRODUCT_CODE